name: Daily Threads Review Request

on:
  schedule:
    # - cron: '5 7 * * *' # 매일 KST 16:05 실행 (UTC 07:05)
    - cron: '30 23 * * *'  # 매일 KST 08:30 실행 (UTC 23:30)
    - cron: '00 00 * * *'  
  workflow_dispatch: 

jobs:
  run-logger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3에서 v4로 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5 # v4에서 v5로 업데이트
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          MY_SLACK_ID: ${{ secrets.MY_SLACK_ID }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: python publish_threads.py
